# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180321_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='creation_at',
            new_name='created_at',
        ),
    ]
