# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180321_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
