# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_topic_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
