# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_topic_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subcomment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comment', to='services.Comment', verbose_name='Comment'),
        ),
    ]
