# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20180323_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.URLField(blank=True, null=True),
        ),
    ]
