# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_comment_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subcomment_count',
        ),
    ]
