# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-27 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_comment_subcomment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='upvotes',
            new_name='up_votes',
        ),
    ]
