# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20180328_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=500, verbose_name='text'),
        ),
    ]
