# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-30 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20180330_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='up_votes',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='up_votes',
        ),
    ]
