# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-02 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20180330_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='services.Topic', verbose_name='Topic'),
        ),
    ]
