# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-02 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20180402_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
